#ifndef QUAN_MATTERS_TEST_FIXED_QUANTITY_SEMANTICS_TEST_HPP_INCLUDED_30_12_2006
#define QUAN_MATTERS_TEST_FIXED_QUANTITY_SEMANTICS_TEST_HPP_INCLUDED_30_12_2006

#include <quan_matters/test/simple_test.hpp>

#endif
