#ifndef QUAN_AVR_LIMITS_HPP_INCLUDED
#define QUAN_AVR_LIMITS_HPP_INCLUDED

#ifndef  __STDC_LIMIT_MACROS
#define  __STDC_LIMIT_MACROS
#include <limits.h>
#define INT32_MAX  0x7FFFFFFF
#define LLONG_MAX  0x7FFFFFFFFFFFFFFFLL

#define LLONG_MIN (-LONG_MAX -1)

#define ULLONG_MAX 0xFFFFFFFFFFFFFFFFULL


#endif

#endif // QUAN_AVR_LIMITS_HPP_INCLUDED
