#ifndef QUAN_MACRO_CAT_HPP_INCLUDED
#define QUAN_MACRO_CAT_HPP_INCLUDED

#define QUAN_MACRO_CAT(A,B) QUAN_MACRO_CAT_IMPL(A,B)
#define QUAN_MACRO_CAT_IMPL(A,B) QUAN_MACRO_CAT_IMPL2(A,B)
#define QUAN_MACRO_CAT_IMPL2(A,B) A##B 

#endif

